// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZenBotCS.Entities;

#nullable disable

namespace ZenBotCS.Migrations.BotDb
{
    [DbContext(typeof(BotDataContext))]
    [Migration("20250613163340_AddLeadershipLog")]
    partial class AddLeadershipLog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("LeadershipLogMessageLeadershipLogPlayerTag", b =>
                {
                    b.Property<int>("MentionedPlayerTagsId")
                        .HasColumnType("int");

                    b.Property<ulong>("MessagesMentionedInId")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("MentionedPlayerTagsId", "MessagesMentionedInId");

                    b.HasIndex("MessagesMentionedInId");

                    b.ToTable("LeadershipLogMessageLeadershipLogPlayerTag");
                });

            modelBuilder.Entity("LeadershipLogMessageLeadershipLogUser", b =>
                {
                    b.Property<ulong>("MentionedUsersId")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("MessagesMentionedInId")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("MentionedUsersId", "MessagesMentionedInId");

                    b.HasIndex("MessagesMentionedInId");

                    b.ToTable("LeadershipLogMessageLeadershipLogUser");
                });

            modelBuilder.Entity("ZenBotCS.Entities.Models.ClanSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CcGoldDump")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ChampStyleCwlRoster")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ClanTag")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("ClanType")
                        .HasColumnType("int");

                    b.Property<string>("ColorHex")
                        .HasMaxLength(9)
                        .HasColumnType("varchar(9)");

                    b.Property<ulong?>("CwlRoleId")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong?>("ElderRoleId")
                        .HasColumnType("bigint unsigned");

                    b.Property<bool>("EnableCwlSignup")
                        .HasColumnType("tinyint(1)");

                    b.Property<ulong?>("LeaderRoleId")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong?>("MemberRoleId")
                        .HasColumnType("bigint unsigned");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ClanSettings");
                });

            modelBuilder.Entity("ZenBotCS.Entities.Models.CwlSignup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Archieved")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Bonus")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ClanTag")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)");

                    b.Property<ulong>("DiscordId")
                        .HasColumnType("bigint unsigned");

                    b.Property<bool>("MaxDefeneses")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("OptOutDays")
                        .HasColumnType("int");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PlayerTag")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)");

                    b.Property<int>("PlayerThLevel")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("WarGeneral")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("WarPreference")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CwlSignups");
                });

            modelBuilder.Entity("ZenBotCS.Entities.Models.DiscordLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<ulong>("DiscordId")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("PlayerTag")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("PlayerTag")
                        .IsUnique();

                    b.HasIndex("PlayerTag", "DiscordId")
                        .IsUnique();

                    b.ToTable("DiscordLinks");
                });

            modelBuilder.Entity("ZenBotCS.Entities.Models.LeadershipLogMessage", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<ulong>("ChannelId")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("FullContent")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("LeadershipLogMessages");
                });

            modelBuilder.Entity("ZenBotCS.Entities.Models.LeadershipLogPlayerTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Tag")
                        .IsUnique();

                    b.ToTable("LeadershipLogPlayerTags");
                });

            modelBuilder.Entity("ZenBotCS.Entities.Models.LeadershipLogUser", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.HasKey("Id");

                    b.ToTable("LeadershipLogUsers");
                });

            modelBuilder.Entity("ZenBotCS.Entities.Models.PinnedRoster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClanTag")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Gid")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SpreadsheetId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ClanTag")
                        .IsUnique();

                    b.ToTable("PinnedRosters");
                });

            modelBuilder.Entity("ZenBotCS.Entities.Models.PlayerStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Player")
                        .HasColumnType("longtext");

                    b.Property<string>("PlayerTag")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PlayerWarhits")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("PlayerStats");
                });

            modelBuilder.Entity("ZenBotCS.Entities.Models.ReminderMisses", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<ulong>("ChannelId")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("ClanTag")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<ulong?>("PingRoleId")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId", "ClanTag")
                        .IsUnique();

                    b.ToTable("ReminderMisses");
                });

            modelBuilder.Entity("ZenBotCS.Entities.Models.WarHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClanTag")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("WarData")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("WarHistories");
                });

            modelBuilder.Entity("LeadershipLogMessageLeadershipLogPlayerTag", b =>
                {
                    b.HasOne("ZenBotCS.Entities.Models.LeadershipLogPlayerTag", null)
                        .WithMany()
                        .HasForeignKey("MentionedPlayerTagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZenBotCS.Entities.Models.LeadershipLogMessage", null)
                        .WithMany()
                        .HasForeignKey("MessagesMentionedInId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LeadershipLogMessageLeadershipLogUser", b =>
                {
                    b.HasOne("ZenBotCS.Entities.Models.LeadershipLogUser", null)
                        .WithMany()
                        .HasForeignKey("MentionedUsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZenBotCS.Entities.Models.LeadershipLogMessage", null)
                        .WithMany()
                        .HasForeignKey("MessagesMentionedInId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
